from app.models import db, Brewery

breweries = [
    {
        "name": "Seven Stills",
        "owner_id": 1,
        "profile_image_id": 1,
        # "banner_image_id": 2,
        "brewery_type": "micro",
        "street": "1439 Egbert Ave Unit C",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94124-3221",
        "country": "United States",
        "phone": "4159140936",
        "website_url": "http://www.sevenstillsofsf.com",
    },
    {
        "name": "47 Hills Brewing Co",
        "owner_id": 2,
        "profile_image_id": 3,
        # "banner_image_id": 4,
        "brewery_type": "brewpub",
        "street": "137 S Linden Ave",
        "city": "South San Francisco",
        "state": "California",
        "postal_code": "94080-6410",
        "country": "United States",
        "phone": "6508678476",
        "website_url": "http://47hillsbrewingcompany.com",
    },
    {
        "name": "Anchor Brewing Co",
        "owner_id": 3,
        "profile_image_id": 5,
        # "banner_image_id": 6,
        "brewery_type": "large",
        "street": "1705 Mariposa St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107-2334",
        "country": "United States",
        "phone": "4158638350",
        "website_url": "http://www.anchorbrewing.com",
    },
    {
        "name": "Armstrong Brewing Co",
        "owner_id": 4,
        "profile_image_id": 7,
        # "banner_image_id": 8,
        "brewery_type": "micro",
        "street": "415 Grand Ave Ste 103",
        "city": "South San Francisco",
        "state": "California",
        "postal_code": "94080-3614",
        "country": "United States",
        "phone": "6509898447",
        "website_url": "http://www.armstrongbrewing.com",
    },
    {
        "name": "Barebottle Brewing Company",
        "owner_id": 5,
        "profile_image_id": 9,
        # "banner_image_id": 10,
        "brewery_type": "micro",
        "street": "1525 Cortland Ave",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94110-5714",
        "country": "United States",
        "phone": "4159268617",
        "website_url": "http://www.barebottlebeer.com",
    },
    {
        "name": "Barrel Head Brewhouse",
        "owner_id": 6,
        "profile_image_id": 11,
        # "banner_image_id": 12,
        "brewery_type": "brewpub",
        "street": "1785 Fulton St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94117-1202",
        "country": "United States",
        "phone": "4154166989",
        "website_url": "http://www.barrelheadsf.com",
    },
    {
        "name": "Black Hammer Brewing",
        "owner_id": 7,
        "profile_image_id": 13,
        # "banner_image_id": 14,
        "brewery_type": "micro",
        "street": "544 Bryant St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107-1217",
        "country": "United States",
        "phone": "4155002273",
        "website_url": "http://www.blackhammerbrewing.com",
    },
    {
        "name": "Cellarmaker Brewing Company",
        "owner_id": 8,
        "profile_image_id": 15,
        # "banner_image_id": 16,
        "brewery_type": "micro",
        "street": "1150 Howard St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94103-3914",
        "country": "United States",
        "phone": "4158633940",
        "website_url": "http://www.cellarmakerbrewing.com",
    },
    {
        "name": "Fort Point Beer Company",
        "owner_id": 9,
        "profile_image_id": 17,
        # "banner_image_id": 18,
        "brewery_type": "regional",
        "street": "644 Mason St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94129-1600",
        "country": "United States",
        "phone": "4159064021",
        "website_url": "http://www.fortpointbeer.com",
    },
    {
        "name": "Harmonic Brewing",
        "owner_id": 10,
        "profile_image_id": 19,
        # "banner_image_id": 20,
        "brewery_type": "micro",
        "street": "1050 26th St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107-3513",
        "country": "United States",
        "phone": "4158726817",
        "website_url": "http://www.harmonicbrewing.com",
    },
    {
        "name": "Laughing Monk Brewing",
        "owner_id": 11,
        "profile_image_id": 21,
        "banner_image_id": 22,
        "brewery_type": "micro",
        "street": "1439 Egbert Ave Unit A",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94124-3221",
        "country": "United States",
        "phone": "4158905970",
        "website_url": "http://www.laughingmonkbrewing.com",
    },
    {
        "name": "Local Brewing Co",
        "owner_id": 12,
        "profile_image_id": 23,
        # "banner_image_id": 24,
        "brewery_type": "micro",
        "street": "69 Bluxome St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107-1605",
        "country": "United States",
        "phone": "4158647468",
        "website_url": "http://www.localbrewingco.com",
    },
    {
        "name": "Magnolia Brewing Company",
        "owner_id": 13,
        "profile_image_id": 25,
        # "banner_image_id": 26,
        "brewery_type": "brewpub",
        "street": "1398 Haight St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94117-2909",
        "country": "United States",
        "phone": "4158647468",
        "website_url": "https://magnoliabrewing.com/",
    },
    {
        "name": "Ale Industries",
        "owner_id": 14,
        "profile_image_id": 27,
        # "banner_image_id": 28,
        "brewery_type": "micro",
        "street": "3096 E 10th St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94601-2960",
        "country": "United States",
        "phone": "9254705280",
        "website_url": "http://www.aleindustries.com",
    },
    {
        "name": "Diving Dog Brewhouse",
        "owner_id": 15,
        "profile_image_id": 29,
        # "banner_image_id": 30,
        "brewery_type": "micro",
        "street": "1802 Telegraph Ave",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94612-2110",
        "latitude": "37.807739",
        "phone": "5103061914",
        "website_url": "http://www.divingdogbrew.com",
    },
    {
        "name": "Federation Brewing",
        "owner_id": 16,
        "profile_image_id": 31,
        "banner_image_id": 32,
        "brewery_type": "micro",
        "street": "420 3rd St Unit A",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607-3809",
        "country": "United States",
        "phone": "5104964228",
        "website_url": "http://www.federationbrewing.com",
    },
    {
        "name": "Funky Buddha Brewery",
        "owner_id": 17,
        "profile_image_id": 33,
        # "banner_image_id": 34,
        "brewery_type": "large",
        "street": "1201 NE 38th St Ste A1 Bay A1",
        "city": "Oakland Park",
        "state": "Florida",
        "postal_code": "33334-4504",
        "country": "United States",
        "phone": "9544400046",
        "website_url": "http://www.thefunkybuddha.com",
    },
    {
        "name": "Ghost Town Brewing",
        "owner_id": 18,
        "profile_image_id": 35,
        # "banner_image_id": 36,
        "brewery_type": "micro",
        "street": "1960 Adeline St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607-2300",
        "country": "United States",
        "phone": "5109266728",
        "website_url": "http://www.ghosttownbrewing.com",
    },
    {
        "name": "Independent Brewing Co",
        "owner_id": 19,
        "profile_image_id": 37,
        # "banner_image_id": 38,
        "brewery_type": "micro",
        "street": "444 Harrison St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607-4118",
        "country": "United States",
        "phone": "5109266728",
        "website_url": "http://independentbrewing.com",
    },
    {
        "name": "Lucky Devil Brewing",
        "owner_id": 20,
        "profile_image_id": 39,
        # "banner_image_id": 40,
        "brewery_type": "micro",
        "street": "Frank H Ogawa Pl",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94612",
        "country": "United States",
        "phone": "5109692865",
        "website_url": "http://www.luckydevilbrewery.com",
    },
]


def seed_breweries():
    for brewery in breweries:
        new_brewery = Brewery(
            name=brewery["name"],
            owner_id=brewery["owner_id"],
            profile_image_id=brewery["profile_image_id"],
            # banner_image_id = brewery["banner_image_id"],
            brewery_type=brewery["brewery_type"],
            street=brewery["street"],
            city=brewery["city"],
            state=brewery["state"],
            postal_code=brewery["postal_code"],
            country=brewery["country"],
            phone=brewery["phone"],
            website_url=brewery["website_url"])
        db.session.add(new_brewery)
    db.session.commit()


def undo_breweries():
    db.session.execute('TRUNCATE breweries RESTART IDENTITY CASCADE;')
    db.session.commit()
