from app.models import db, Brewery

breweries = [
    {
        "name": "Seven Stills",
        "owner_id": 8,
        "profile_image": "https://sfbeerweek.org/assets/14/14-fb1b134df7f7cbfa5f5ee4e495185.jpg",
        # "banner_image": "https://thecraftycask.com/wp-content/uploads/2019/05/IMG_5646-1080x675_1e7961afb0e86b8f45b9f5c9e5969465_2000.jpg",
        "header": "Warehouse-style destination featuring a whiskey distillery, plus small plates, cocktails & beer.",
        "description": "Seven Stills was founded by UC Santa Cruz grads, Tim Obert and Clint Potter in 2013. After a round of beers Clint began telling Tim about a class he was taking on Whiskey Production and how he had learned that whiskey was made from a low quality beer. Tim, an avid homebrewer asked what would happen if they distilled some of his home brewed beers. Clint, responded that he didn't know and after another round of beers the due purchased a 10 gallon pot still online to test their idea out.Seven Stills was borne after a year of trial and error.  Tim and Clint pitched in their life savings, rented a 400 gallon storage unit in the Dogpatch and got to work making their dreams of starting a Whiskey Distillery a reality.",
        "brewery_type": "micro",
        "street": "1439 Egbert Ave Unit C",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94124",
        "country": "United States",
        "phone": "4159140936",
        # "website_url": "http://www.sevenstillsofsf.com",
    },
    {
        "name": "47 Hills Brewing Co",
        "owner_id": 2,
        "profile_image": "https://untappd.akamaized.net/site/brewery_logos_hd/brewery-325256_26582_hd.jpeg",
        # "banner_image": "https://media-cdn.tripadvisor.com/media/photo-m/1280/14/8b/ae/80/47-hills-brewing-company.jpg",
        "header": "Innovative brewing. Traditional roots.",
        "description": "Enriching the community is the singular goal of 47 Hills Brewing Company. We cherish our employees and customers and create the most balanced and interesting beers we can by using innovative brewing traditions and environmentally sensible practice. Our taproom encourages all walks of life to take part in lively conversations and togetherness. Within our doors, the elements of a healthy community come alive.",
        "brewery_type": "brewpub",
        "street": "137 S Linden Ave",
        "city": "South San Francisco",
        "state": "California",
        "postal_code": "94080",
        "country": "United States",
        "phone": "6508678476",
        # "website_url": "http://47hillsbrewingcompany.com",
    },
    {
        "name": "Anchor Brewing Co",
        "owner_id": 3,
        "profile_image": "https://s.hdnux.com/photos/0/0/0/17629041/4/900x0.jpg",
        # "banner_image": "https://www.visitcalifornia.com/sites/visitcalifornia.com/files/styles/welcome_image/public/VC_Breweries_Module7_AnchorBrewing_Supplied_brewhouse-wide_1280x640.jpg",
        "header": "Raise Anchor to the next 125 years!",
        "description": "Forged in San Francisco in 1896, we are proud to be America's First Craft Brewery. As we celebrate and honor our 125 years of trailblazing tradition, we're looking ahead to our next 125. Anchors raised and full Steam ahead.",
        "brewery_type": "large",
        "street": "1705 Mariposa St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107",
        "country": "United States",
        "phone": "4158638350",
        # "website_url": "http://www.anchorbrewing.com",
    },
    {
        "name": "Armstrong Brewing Co",
        "owner_id": 4,
        "profile_image": "https://everythingsouthcity.com/wp-content/uploads/2019/09/armstrong-logo.jpg",
        # "banner_image": "https://s.hdnux.com/photos/01/13/41/12/19796626/3/rawImage.jpg",
        "header": "Good Beer, Good Friends, Good Times",
        "description": "Crafted in the heart of the Industrial City, our taps are ever-rotating with innovative, small-batch beer - sometimes barrel aged or kettle soured, other times simply experimental. We pride ourself on bringing our patrons a unique, vibrant experience. ",
        "brewery_type": "micro",
        "street": "415 Grand Ave Ste 103",
        "city": "South San Francisco",
        "state": "California",
        "postal_code": "94080",
        "country": "United States",
        "phone": "6509898447",
        # "website_url": "https://www.facebook.com/ArmstrongBrewing/",
    },
    {
        "name": "Barebottle Brewing Company",
        "owner_id": 5,
        "profile_image": "https://images.squarespace-cdn.com/content/v1/581a2d252994ca082120e432/1501624389786-XAIEI4N3ZOOPUW4GVRZG/whitelogo.png",
        # "banner_image": "https://www.itasteit.com/media/reviews/photos/thumbnail/1500x500s/2a/bb/e6/barebottle-brewing-company-98-1466619627.jpg",
        "header": "Welcome to Barebottle!  Our taprooms are open and do not require reservations, so please stop by anytime.",
        "description": "Over many years of entering and judging beer competitions, we noticed a simple, but largely unrecognized insight: some of the best, most innovative beers in America are being brewed by homebrewers. In almost every competition we judged, the award-winning homebrewed beers were more inventive and daring than the majority of commercially available beers on the market. That insight, along with an enduring passion for the craft of beer making, led us to create Barebottle, a San Francisco crowd-inspired craft brewery. Barebottle Brewing Company was co-founded by Lester Koga, Michael Seitz, and Ben Sterling, three friends and former classmates at Cornell Business School in Ithaca, NY. After moving from Ithaca to the Bay Area in 2007, the three began homebrewing, became certified beer judges, and began winning medals at homebrewing competitions. Barebottle brews innovative beers inspired by the San Francisco Bay Area using local ingredients wherever possible, and partners with local homebrewing groups to develop new beers using a competitive method.",
        "brewery_type": "micro",
        "street": "1525 Cortland Ave",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94110",
        "country": "United States",
        "phone": "4159268617",
        # "website_url": "http://www.barebottlebeer.com",
    },
    {
        "name": "Barrel Head Brewhouse",
        "owner_id": 6,
        "profile_image": "https://pbs.twimg.com/profile_images/420293260016230400/Ow5quOHL_400x400.jpeg",
        # "banner_image": "https://juliesfreebies.com/wp-content/uploads/2021/05/barrellhead.jpg",
        "header": "Look how cool our logo is ;)",
        "description": "Drink with us! We'll drink your head off right into a barrell!",
        "brewery_type": "brewpub",
        "street": "1785 Fulton St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94117",
        "country": "United States",
        "phone": "4154166989",
        # "website_url": "http://www.barrelheadsf.com",
    },
    {
        "name": "Black Hammer Brewing",
        "owner_id": 7,
        "profile_image": "https://pbs.twimg.com/profile_images/885917064828862464/ErVbyAIR_400x400.jpg",
        # "banner_image": "https://bier-traveller.com/wp-content/uploads/2018/09/San-Francisco-Bier-Traveller.com-Jun2-29-1.jpg",
        "header": "Small-production brews & tasting flights poured in a lofty, modern warehouse space with free Wi-Fi.",
        "description": "Black Hammer Brewing focuses on superbly balanced lagers, ales and hard seltzers at our brewery in San Francisco, California. We are considered the only Burner Brewery in existence today, and our name comes from the nickname of our co-founder, Jim 'Hammer' Furman, semi-portmanteaued with the name of Burning Man's iconic Black Rock City. Our quest is to promote radical inclusivity as well as radical self-expression, through our brewery & beer, our staff, locations, guests and events, and to ensure that you feel as welcome and appreciated as you truly are.",
        "brewery_type": "micro",
        "street": "544 Bryant St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107",
        "country": "United States",
        "phone": "4155002273",
        # "website_url": "http://www.blackhammerbrewing.com",
    },
    {
        "name": "Cellarmaker Brewing Company",
        "owner_id": 1,
        "profile_image": "https://pbs.twimg.com/profile_images/804035762555469824/smxXVED7_400x400.jpg",
        # "banner_image": "https://viatravelers.com/wp-content/uploads/2021/11/Cellarmaker-Brewing-Company.jpg",
        "header": "Contemporary exposed-brick tasting room offering a rotating selection of small-batch brews on tap.",
        "description": "We are a San Francisco brewery producing our beers in small batches one beer at a time. It is our goal to keep your taste buds intrigued by constantly producing different flavors. To us, making the same 3-4 beers all the time would be boring. We hope you feel the same way. Our limited output and choice to abandon the common concept of a set production schedule will allow us to constantly experiment with different hops, barrels, and yeasts.",
        "brewery_type": "micro",
        "street": "1150 Howard St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94103",
        "country": "United States",
        "phone": "4158633940",
        # "website_url": "http://www.cellarmakerbrewing.com",
    },
    {
        "name": "Fort Point Beer Company",
        "owner_id": 9,
        "profile_image": "https://d2pxm94gkd1wuq.cloudfront.net/BreweryLogos/Standard/7442.fort-point-beer-company.jpg",
        # "banner_image": "https://www.firstrepublic.com/-/media/frb/images/articles/articles-2019/745x390-client-spotlight-why-fort-point-beer-company-is-thriving-in-a-competitive-market.jpg",
        "header": "Prost!",
        "description": "Fort Point is an independent San Francisco beer company made up of people who believe the simple things in life can be a whole lot better.",
        "brewery_type": "regional",
        "street": "644 Mason St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94129",
        "country": "United States",
        "phone": "4159064021",
        # "website_url": "http://www.fortpointbeer.com",
    },
    {
        "name": "Harmonic Brewing",
        "owner_id": 10,
        "profile_image": "https://pbs.twimg.com/profile_images/1290478841878568960/l5ffXIW7_400x400.jpg",
        # "banner_image": "https://www.bayareamade.us/wp-content/uploads/beans/images/Harmonic-2v-7ffcb07.jpg",
        "header": "Brewery serving its own craft beers plus snacks & food truck fare in lofty, polished warehouse digs.",
        "description": "We are an independent brewery that celebrates Craft, Culture, and Community in San Francisco.",
        "brewery_type": "micro",
        "street": "1050 26th St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107",
        "country": "United States",
        "phone": "4158726817",
        # "website_url": "http://www.harmonicbrewing.com",
    },
    {
        "name": "Laughing Monk Brewing",
        "owner_id": 11,
        "profile_image": "https://i.pinimg.com/originals/cb/f8/07/cbf807339acd40601b2e9112eb2da6ca.png",
        # "banner_image": "https://images.squarespace-cdn.com/content/v1/56e88f0420c64741f20eecc3/1524614540541-L8RX31RLFAKJI16EHZLO/0U3A9778_web.jpg",
        "header": "Neighborhood alehouse with housemade brews & order-in eats served in a bright, convivial space.",
        "description": "Every adventure needs to start somewhere. Ours began as beer fans growing up on the hoppy pales of California, but our curiosity didn’t let us stop there. We kept exploring the vast world of beer and, like many before us, found Belgium. Where California celebrates bright, citrusy, resiny hops, Belgium is all about subtle malt and expressive yeast. We draw from both these heritages to create uniquely delicious new beers",
        "brewery_type": "micro",
        "street": "1439 Egbert Ave Unit A",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94124",
        "country": "United States",
        "phone": "4158905970",
        # "website_url": "http://www.laughingmonkbrewing.com",
    },
    {
        "name": "Local Brewing Co",
        "owner_id": 12,
        "profile_image": "https://localbrewingco.com/cms/wp-content/themes/lbc/img/beers/beer-goblet-medium-dark.png",
        # "banner_image": "https://cloudinary-assets.dostuffmedia.com/res/dostuff-media/image/upload/venue-396045/1492190815.jpg",
        "header": "Brewery serving original IPAs, lagers & more, plus American fare at night, in a relaxed space.",
        "description": "The kind of brews you can enjoy more than one of and won’t be bored with. We use the finest ingredients we can get our hands on from the closest purveyors possible.",
        "brewery_type": "micro",
        "street": "69 Bluxome St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94107",
        "country": "United States",
        "phone": "4158647468",
        # "website_url": "http://www.localbrewingco.com",
    },
    {
        "name": "Magnolia Brewing Company",
        "owner_id": 13,
        "profile_image": "https://d1ynl4hb5mx7r8.cloudfront.net/wp-content/uploads/2018/10/02080257/92b832c1f15e938b5455.png",
        # "banner_image": "https://resizer.otstatic.com/v2/photos/wide-huge/3/42779280.jpg",
        "header": "The Pub where it all began.",
        "description": "Magnolia opened 20 years ago at the storied corner of Haight and Masonic Streets in the Haight Ashbury district. Built in 1903, our building has seen a lot over the years, from its decades as Schumates Pharmacy to its role in the birth of the Haight Ashbury hippie movement in 1964 as the Drugstore Cafe, one of the original hippie hangouts in the neighborhood. In the late 60s, it became the famous Magnolia Thunderpussy's, named for its proprietress, a larger than life San Francisco legend still talked about today.",
        "brewery_type": "brewpub",
        "street": "1398 Haight St",
        "city": "San Francisco",
        "state": "California",
        "postal_code": "94117",
        "country": "United States",
        "phone": "4158647468",
        # "website_url": "https://magnoliabrewing.com/",
    },
    {
        "name": "Ale Industries",
        "owner_id": 14,
        "profile_image": "https://pbs.twimg.com/profile_images/689590365901336576/XBRvAIHm_400x400.jpg",
        # "banner_image": "https://bartable.bart.gov/sites/default/files/styles/body_width_/public/images/discoveries/AleIndustries-FB.jpg",
        "header": "Chill taproom inside a warehouselike brewery offering a variety of house beers plus growlers to go.",
        "description": "Ale Industries is an environmentally conscious endeavor that uniquely spreads the experience of craft beer from Oakland's Fruitvale district.",
        "brewery_type": "micro",
        "street": "3096 E 10th St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94601",
        "country": "United States",
        "phone": "9254705280",
        # "website_url": "http://www.aleindustries.com",
    },
    {
        "name": "Diving Dog Brewhouse",
        "owner_id": 15,
        "profile_image": "https://d2pxm94gkd1wuq.cloudfront.net/BreweryLogos/Standard/397393838.divingdogbrewhouse.jpg",
        # "banner_image": "https://cdn.vox-cdn.com/thumbor/WdKTnUZRBG4tr1WRaJsKiCqB8ls=/0x0:1500x807/1200x800/filters:focal(630x284:870x524)/cdn.vox-cdn.com/uploads/chorus_image/image/65111837/dog_photos_above_kettles_resize_1500x807.0.jpg",
        "header": "We are closed :(",
        "description": " We are now officially closed :(",
        "brewery_type": "micro",
        "street": "1802 Telegraph Ave",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94612",
        "country": "United States",
        "phone": "5103061914",
        # "website_url": "http://www.divingdogbrew.com",
    },
    {
        "name": "Federation Brewing",
        "owner_id": 16,
        "profile_image": "https://drinkbaybeer.com/assets/17/17-c8251448cf0ef9d779c7296dd071e.png",
        # "banner_image": "https://images.squarespace-cdn.com/content/v1/5c16d35a7e3c3a927a76ec36/1584849061818-MNYYO5LQJD0FFWRM6ULV/FEd+Front+of+Building+%281%29.jpeg",
        "header": "A laid-back neighborhood tasting room & tavern offering house beers & live tunes.",
        "description": "Craft beer focused on balanced flavor profiles and sourcing the finest local ingredients. Small batch producers of award winning craft beer.",
        "brewery_type": "micro",
        "street": "420 3rd St Unit A",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607",
        "country": "United States",
        "phone": "5104964228",
        # "website_url": "http://www.federationbrewing.com",
    },
    {
        "name": "Funky Buddha Brewery",
        "owner_id": 17,
        "profile_image": "https://upload.wikimedia.org/wikipedia/en/b/b7/FunkyBuddhaLogo.jpg",
        # "banner_image": "https://media2.miaminewtimes.com/mia/imager/u/original/9411823/new_times_funky_buddha-7165.jpg",
        "header": "Offering tours on weekends, this large craft brewery features a no-frills taproom with games.",
        "description": "From traditional styles to experimental ales, we make beers that create an experience. Beer that reminds us to be creative, celebrate being different, and always keep things Funky.",
        "brewery_type": "large",
        "street": "1201 NE 38th St Ste A1 Bay A1",
        "city": "Oakland Park",
        "state": "Florida",
        "postal_code": "33334",
        "country": "United States",
        "phone": "9544400046",
        # "website_url": "http://www.thefunkybuddha.com",
    },
    {
        "name": "Ghost Town Brewing",
        "owner_id": 18,
        "profile_image": "https://images.editor.website/uploads/b/cbcb8c00-6983-11ea-8683-23d0eb73c404/GTB_Logo.png",
        # "banner_image": "https://images.squarespace-cdn.com/content/v1/5abc00a1c258b4f56d094ecc/1526193436940-KH8O482HTZUKS1JMZJ1N/40092310410_1571298bfc_k-1.jpg",
        "header": "The scariest beer in town.",
        "description": "Warehouse brewery & taproom serving house-crafted pints & growlers in low-key, spacious surrounds.",
        "brewery_type": "micro",
        "street": "1960 Adeline St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607",
        "country": "United States",
        "phone": "5109266728",
        # "website_url": "http://www.ghosttownbrewing.com",
    },
    {
        "name": "Independent Brewing Co",
        "owner_id": 19,
        "profile_image": "https://pbs.twimg.com/profile_images/681682320911237122/RcoiyJh9_400x400.jpg",
        # "banner_image": "https://cdn.hopculture.com/wp-content/uploads/2017/01/The-Independent-Brewing-Lead.jpg",
        "header": "All in house ingredients. Fully Independent",
        "description": "All in house ingredients. Fully Independent.",
        "brewery_type": "micro",
        "street": "444 Harrison St",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94607",
        "country": "United States",
        "phone": "5109266728",
        # "website_url": "http://independentbrewing.com",
    },
    {
        "name": "Lucky Devil Brewing",
        "owner_id": 20,
        "profile_image": "https://pbs.twimg.com/profile_images/1085257517641486337/7nxEF3jQ_400x400.jpg",
        # "banner_image": "https://images.squarespace-cdn.com/content/v1/54613e97e4b00403fdda207f/1642450215996-ZWKKRZVR2NWTMG0V27RG/IMG_6569.jpg",
        "header": "You'll be saying 'Bloody Devil! That is good!",
        "description": "Lucky Devil is a Belgian inspired brewing company based out of Oakland California, founded by Master Brewer Paul Wichelmann.",
        "brewery_type": "micro",
        "street": "Frank H Ogawa Pl",
        "city": "Oakland",
        "state": "California",
        "postal_code": "94612",
        "country": "United States",
        "phone": "5109692865",
        # "website_url": "http://www.luckydevilbrewery.com",
    },
]

# print(breweries)

def seed_breweries():
    for brewery in breweries:
        new_brewery = Brewery(
            name=brewery["name"],
            owner_id=brewery["owner_id"],
            profile_image=brewery["profile_image"],
            # banner_image = brewery["banner_image"],
            header=brewery['header'],
            description=brewery['description'],
            brewery_type=brewery["brewery_type"],
            street=brewery["street"],
            city=brewery["city"],
            state=brewery["state"],
            postal_code=brewery["postal_code"],
            country=brewery["country"],
            phone=brewery["phone"])
            # website_url=brewery["website_url"])
        db.session.add(new_brewery)
    db.session.commit()


def undo_breweries():
    db.session.execute('TRUNCATE breweries RESTART IDENTITY CASCADE;')
    db.session.commit()
