"""empty message

Revision ID: a1da52b3f8e3
Revises: 97e6e28b5cd3
Create Date: 2022-05-25 18:14:14.860470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1da52b3f8e3'
down_revision = '97e6e28b5cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('beer_image', sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer', 'beer_image')
    # ### end Alembic commands ###
