"""empty message

Revision ID: 2f858c813c52
Revises: 98a7f8479c3a
Create Date: 2022-04-22 12:27:23.673990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f858c813c52'
down_revision = '98a7f8479c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breweries', 'website_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breweries', sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
