"""empty message

Revision ID: faebab09a4cd
Revises: 14890d7fd43c
Create Date: 2022-04-15 19:38:44.943669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faebab09a4cd'
down_revision = '14890d7fd43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=False))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
