"""empty message

Revision ID: 19415d855332
Revises: 3d24a867f276
Create Date: 2022-04-13 21:17:48.773326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19415d855332'
down_revision = '3d24a867f276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'profile_image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
