"""empty message

Revision ID: 98a7f8479c3a
Revises: 4d89a9d284e0
Create Date: 2022-04-22 11:41:55.966005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a7f8479c3a'
down_revision = '4d89a9d284e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('beer_name_key', 'beer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('beer_name_key', 'beer', ['name'])
    # ### end Alembic commands ###
